### ISSUE TITLE
Scheduled Blocks...

### ISSUE THREAD

**Issue by bonelifer** [robwebset/screensaver.tvtunes#1]
It would  be nice to have the ability to schedule a certain block of time that would instead default to the builtin DIM screensaver. For example at night. I have a Raspberry Pi 3 in my bedroom, that I never turn off because it's easier not to and it doesn't support WOL, so makes it hard to update my XMLTV file for the livetv only EPG or autoupdate the texture cache at night when I'm not using the RPi.

**Comment by robwebset** [comment]
Please can you post all requests to the forum, that way other people can see them.

Thanks, Rob
